#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2014, 2017 Martin Ueding <dev@martin-ueding.de>

import argparse
import numpy as np
import matplotlib.pyplot as pl


def main():
    options = _parse_args()

    for filename in options.filenames:
        data = np.loadtxt(filename)

        row_count, column_count = data.shape

        x = data[:, 0]
        y = data[:, 1]

        if column_count == 2:
            pl.plot(x, y, marker='o', label=filename)

        if column_count == 3:
            y_err = data[:, 2]

            pl.errorbar(x, y, yerr=y_err, marker='o', label=filename)


    pl.legend(loc='best')
    pl.grid(True)

    if options.xlog:
        pl.xscale('log')
    if options.ylog:
        pl.yscale('log')

    pl.margins(0.05)

    if options.title is not None:
        pl.title(options.title)
    if options.xlabel is not None:
        pl.xlabel(options.xlabel)
    if options.ylabel is not None:
        pl.ylabel(options.ylabel)

    pl.tight_layout()

    pl.show()


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument('filenames', nargs='+')
    parser.add_argument('--xlog', action='store_true')
    parser.add_argument('--ylog', action='store_true')
    parser.add_argument('--title')
    parser.add_argument('--xlabel')
    parser.add_argument('--ylabel')

    options = parser.parse_args()

    return options


if __name__ == "__main__":
    main()
